version: 0.2

run-as: ec2-user

phases:
  build:
    commands:
      - echo 'Copying index file to apache root directory'
     - cp index.html /var/www/html
artifacts:
  files:
    - index.html
    - appspec.yml
