version: 0.2

run-as: ec2-user

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    run-as: ec2-user
    commands:
      - mkdir '/var/www/html'
  build:
    commands:
      - cp index.html '/var/www/html'
artifacts:
  files:
     - '**/*'
