version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - 'mkdir /var/www/html'
  build:
    commands:
      - cp index.html /var/www/html'
artifacts:
  files:
     - '**/*'
