version: 0.2

run-as: ec2-user

phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - cp index.html /var/www/html
artifacts:
  files:
    - index.html
    - appspec.yml
